//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc5_ile_oyun_blog_sitesi.Models.entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dboyunblogEntities : DbContext
    {
        public dboyunblogEntities()
            : base("name=dboyunblogEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tbl_bloglar> tbl_bloglar { get; set; }
        public virtual DbSet<tbl_hakkımızda> tbl_hakkımızda { get; set; }
        public virtual DbSet<tbl_homegiris> tbl_homegiris { get; set; }
        public virtual DbSet<tbl_iletisim> tbl_iletisim { get; set; }
        public virtual DbSet<tbl_iletisim2> tbl_iletisim2 { get; set; }
        public virtual DbSet<tbl_kategoriler> tbl_kategoriler { get; set; }
        public virtual DbSet<tbl_yorumlar> tbl_yorumlar { get; set; }
        public virtual DbSet<tbl_Admin> tbl_Admin { get; set; }
        public virtual DbSet<tbl_duyurular> tbl_duyurular { get; set; }
        public virtual DbSet<tbl_sosyalmedya> tbl_sosyalmedya { get; set; }
    }
}
