//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc5_ile_oyun_blog_sitesi.Models.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_kategoriler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_kategoriler()
        {
            this.tbl_bloglar = new HashSet<tbl_bloglar>();
        }
    
        public byte Id { get; set; }
        public string KategoriAd { get; set; }
        public Nullable<bool> KategoriSil { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_bloglar> tbl_bloglar { get; set; }
    }
}
