//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc5_ile_oyun_blog_sitesi.Models.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_iletisim2
    {
        public byte Id { get; set; }
        public string AdresBaslik { get; set; }
        public string AdresAciklama { get; set; }
        public string Eposta { get; set; }
        public string Telefon { get; set; }
    }
}
