//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc5_ile_oyun_blog_sitesi.Models.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_yorumlar
    {
        public short Id { get; set; }
        public Nullable<byte> Blog { get; set; }
        public string AdSoyad { get; set; }
        public string Eposta { get; set; }
        public string Yorum { get; set; }
        public Nullable<System.DateTime> YTarih { get; set; }
        public Nullable<bool> YSil { get; set; }
    
        public virtual tbl_bloglar tbl_bloglar { get; set; }
    }
}
